In [726]:
import pandas as pd
import numpy as np

**Datasets taken from**
> https://www.kaggle.com/datasets/muhammadtalhaawan/world-sugar-dataset-2018-2024?select=import_df.csv

In [727]:
df1 = pd.read_csv('/content/export_df.csv')
df2 = pd.read_csv('/content/import_df.csv')

# **Task** 🌟

**Inspect a dataframe with df.head(), df.tail(), df.info(), df.describe().**

* df.head()

In [728]:
df1.head()

        Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
0     Brazil  19,600  19,280  32,150  25,950  28,200     32,398  export
1   Thailand  10,612   6,695   3,739   7,012  11,000     12,000  export
2      India   4,700   5,800   8,406  11,927   6,500      7,000  export
3  Australia   3,735   3,600   3,400   3,120   3,270      3,600  export
4  Guatemala   2,125   1,858   1,395   1,651   1,657      1,662  export

In [729]:
df2.head()

             Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
0       Indonesia   5,362   4,758   6,124   5,466   5,800      5,630  import
1           China   4,086   3,808   6,379   5,000   4,400      5,000  import
2   United_States   2,785   3,778   2,922   3,308   3,126      2,994  import
3      Bangladesh   2,429   2,397   2,351   2,807   2,330      2,700  import
4  European_Union   2,374   2,235   1,792   1,999   3,000      2,500  import

* df.tail()

In [730]:
df1.tail()

           Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
22     Malaysia     123     109     329     316     290        300  export
23  Korea_South     306     313     320     280     260        280  export
24        China     205     189     132     160     202        250  export
25        Other   5,011   4,735   4,492   3,696   4,014      3,706  export
26        Total  58,271  53,536  63,925  64,955  66,085     72,104  export

In [731]:
df2.tail()

          Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
22       Yemen     667     770     941     466     775        875  import
23       Chile     449     648     532     654     640        640  import
24  Kazakhstan     345     482     478     483     580        625  import
25       Other  12,962  12,537  12,422  12,088  12,177     11,653  import
26       Total  53,161  53,735  58,704  56,105  57,527     59,012  import

* df.info()

In [732]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        27 non-null     object
 1   2018/19     27 non-null     object
 2   2019/20     27 non-null     object
 3   2020/21     27 non-null     object
 4   2021/22     27 non-null     object
 5   2022/23     27 non-null     object
 6   May2023/24  27 non-null     object
 7   Action      27 non-null     object
dtypes: object(8)
memory usage: 1.8+ KB

In [733]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        27 non-null     object
 1   2018/19     27 non-null     object
 2   2019/20     27 non-null     object
 3   2020/21     27 non-null     object
 4   2021/22     27 non-null     object
 5   2022/23     27 non-null     object
 6   May2023/24  27 non-null     object
 7   Action      27 non-null     object
dtypes: object(8)
memory usage: 1.8+ KB

* df.describe()

In [734]:
df1.describe()

          Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
count       27      27      27      27      27      27         27      27
unique      27      27      25      26      27      27         26       1
top     Brazil  19,600     300     300  25,950  28,200        300  export
freq         1       1       2       2       1       1          2      27

In [735]:
df2.describe()

             Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
count          27      27      27      27      27      27         27      27
unique         27      27      27      27      27      26         26       1
top     Indonesia   5,362   4,758   6,124   5,466   1,950      1,000  import
freq            1       1       1       1       1       2          2      27

**Creating NaN value**

In [736]:
np.random.seed(10)
col_name=['2021/22', '2022/23']
mask = np.random.choice([True, False], size=df1[col_name].shape)
mask[mask.all(1),-1] = 0
print(mask)
df1[col_name]=df1[col_name].mask(mask)

df1

[[False False]
 [ True False]
 [ True False]
 [False  True]
 [False False]
 [ True False]
 [False  True]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [False False]
 [ True False]
 [False  True]
 [ True False]
 [ True False]
 [ True False]
 [False  True]
 [False False]
 [False False]
 [False  True]
 [False  True]
 [ True False]
 [ True False]
 [ True False]
 [False False]]

           Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
0        Brazil  19,600  19,280  32,150  25,950  28,200     32,398  export
1      Thailand  10,612   6,695   3,739     NaN  11,000     12,000  export
2         India   4,700   5,800   8,406     NaN   6,500      7,000  export
3     Australia   3,735   3,600   3,400   3,120     NaN      3,600  export
4     Guatemala   2,125   1,858   1,395   1,651   1,657      1,662  export
..          ...     ...     ...     ...     ...     ...        ...     ...
22     Malaysia     123     109     329     316     NaN        300  export
23  Korea_South     306     313     320     NaN     260        280  export
24        China     205     189     132     NaN     202        250  export
25        Other   5,011   4,735   4,492     NaN   4,014      3,706  export
26        Total  58,271  53,536  63,925  64,955  66,085     72,104  export

[27 rows x 8 columns]

In [737]:
np.random.seed(10)
col_name=['2021/22', '2022/23']
mask = np.random.choice([True, False], size=df2[col_name].shape)
mask[mask.all(1),-1] = 0
print(mask)
df2[col_name]=df2[col_name].mask(mask)

df2

[[False False]
 [ True False]
 [ True False]
 [False  True]
 [False False]
 [ True False]
 [False  True]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [False False]
 [ True False]
 [False  True]
 [ True False]
 [ True False]
 [ True False]
 [False  True]
 [False False]
 [False False]
 [False  True]
 [False  True]
 [ True False]
 [ True False]
 [ True False]
 [False False]]

              Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
0        Indonesia   5,362   4,758   6,124   5,466   5,800      5,630  import
1            China   4,086   3,808   6,379     NaN   4,400      5,000  import
2    United_States   2,785   3,778   2,922     NaN   3,126      2,994  import
3       Bangladesh   2,429   2,397   2,351   2,807     NaN      2,700  import
4   European_Union   2,374   2,235   1,792   1,999   3,000      2,500  import
..             ...     ...     ...     ...     ...     ...        ...     ...
22           Yemen     667     770     941     466     NaN        875  import
23           Chile     449     648     532     NaN     640        640  import
24      Kazakhstan     345     482     478     NaN     580        625  import
25           Other  12,962  12,537  12,422     NaN  12,177     11,653  import
26           Total  53,161  53,735  58,704  56,105  57,527     59,012  import

[27 rows x 8 columns]

**Show how many missing values in your data, each column.**

In [738]:
df1.isnull().sum()

Name           0
2018/19        0
2019/20        0
2020/21        0
2021/22       15
2022/23        6
May2023/24     0
Action         0
dtype: int64

In [739]:
df2.isnull().sum()

Name           0
2018/19        0
2019/20        0
2020/21        0
2021/22       15
2022/23        6
May2023/24     0
Action         0
dtype: int64

**Manipulate how a dataframe displays in Jupyter by modifying Pandas configuration options such as pd.set_option("display.max_rows", n).**

In [740]:
pd.set_option("display.max_rows", 10)
df1

           Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
0        Brazil  19,600  19,280  32,150  25,950  28,200     32,398  export
1      Thailand  10,612   6,695   3,739     NaN  11,000     12,000  export
2         India   4,700   5,800   8,406     NaN   6,500      7,000  export
3     Australia   3,735   3,600   3,400   3,120     NaN      3,600  export
4     Guatemala   2,125   1,858   1,395   1,651   1,657      1,662  export
..          ...     ...     ...     ...     ...     ...        ...     ...
22     Malaysia     123     109     329     316     NaN        300  export
23  Korea_South     306     313     320     NaN     260        280  export
24        China     205     189     132     NaN     202        250  export
25        Other   5,011   4,735   4,492     NaN   4,014      3,706  export
26        Total  58,271  53,536  63,925  64,955  66,085     72,104  export

[27 rows x 8 columns]

In [741]:
pd.set_option("display.max_rows", 10)
df2

              Name 2018/19 2019/20 2020/21 2021/22 2022/23 May2023/24  Action
0        Indonesia   5,362   4,758   6,124   5,466   5,800      5,630  import
1            China   4,086   3,808   6,379     NaN   4,400      5,000  import
2    United_States   2,785   3,778   2,922     NaN   3,126      2,994  import
3       Bangladesh   2,429   2,397   2,351   2,807     NaN      2,700  import
4   European_Union   2,374   2,235   1,792   1,999   3,000      2,500  import
..             ...     ...     ...     ...     ...     ...        ...     ...
22           Yemen     667     770     941     466     NaN        875  import
23           Chile     449     648     532     NaN     640        640  import
24      Kazakhstan     345     482     478     NaN     580        625  import
25           Other  12,962  12,537  12,422     NaN  12,177     11,653  import
26           Total  53,161  53,735  58,704  56,105  57,527     59,012  import

[27 rows x 8 columns]

**Rename columns of a dataframe using the df.rename() function or by accessing the df.columns attribute.**

In [742]:
df1.rename(columns = {'Name': 'Country',
                      '2018/19': '2018 - 2019',
                      '2019/20': '2019 - 2020',
                      '2020/21': '2020 - 2021',
                      '2021/22': '2021 - 2022',
                      '2022/23': '2022 - 2023',
                      'May2023/24': 'May 2023 - 2024'}, inplace = True)

df1.columns

Index(['Country', '2018 - 2019', '2019 - 2020', '2020 - 2021', '2021 - 2022',
       '2022 - 2023', 'May 2023 - 2024', 'Action'],
      dtype='object')

In [743]:
df2.rename(columns = {'Name': 'Country',
                      '2018/19': '2018 - 2019',
                      '2019/20': '2019 - 2020',
                      '2020/21': '2020 - 2021',
                      '2021/22': '2021 - 2022',
                      '2022/23': '2022 - 2023',
                      'May2023/24': 'May 2023 - 2024'}, inplace = True)

df2.columns

Index(['Country', '2018 - 2019', '2019 - 2020', '2020 - 2021', '2021 - 2022',
       '2022 - 2023', 'May 2023 - 2024', 'Action'],
      dtype='object')

**Modify the index name and index values of a dataframe using .set_index(), .reset_index() , df.index.name, .index.**

* .set_index()

In [744]:
df1.set_index('Country')

,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Country,,,,,,,
Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export
Thailand,"10,612","6,695","3,739",NaN,"11,000","12,000",export
India,"4,700","5,800","8,406",NaN,"6,500","7,000",export
Australia,"3,735","3,600","3,400","3,120",NaN,"3,600",export
Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export
...,...,...,...,...,...,...,...
Malaysia,123,109,329,316,NaN,300,export
Korea_South,306,313,320,NaN,260,280,export
China,205,189,132,NaN,202,250,export
Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export
Total,"58,271","53,536","63,925","64,955","66,085","72,104",export

In [745]:
df2.set_index('Country')

,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Country,,,,,,,
Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import
China,"4,086","3,808","6,379",NaN,"4,400","5,000",import
United_States,"2,785","3,778","2,922",NaN,"3,126","2,994",import
Bangladesh,"2,429","2,397","2,351","2,807",NaN,"2,700",import
European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import
...,...,...,...,...,...,...,...
Yemen,667,770,941,466,NaN,875,import
Chile,449,648,532,NaN,640,640,import
Kazakhstan,345,482,478,NaN,580,625,import
Other,"12,962","12,537","12,422",NaN,"12,177","11,653",import
Total,"53,161","53,735","58,704","56,105","57,527","59,012",import

* .reset_index()

In [746]:
df1.reset_index()

,index,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
0,0,Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export
1,1,Thailand,"10,612","6,695","3,739",NaN,"11,000","12,000",export
2,2,India,"4,700","5,800","8,406",NaN,"6,500","7,000",export
3,3,Australia,"3,735","3,600","3,400","3,120",NaN,"3,600",export
4,4,Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export
...,...,...,...,...,...,...,...,...,...
22,22,Malaysia,123,109,329,316,NaN,300,export
23,23,Korea_South,306,313,320,NaN,260,280,export
24,24,China,205,189,132,NaN,202,250,export
25,25,Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export
26,26,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export

In [747]:
df2.reset_index()

,index,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
0,0,Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import
1,1,China,"4,086","3,808","6,379",NaN,"4,400","5,000",import
2,2,United_States,"2,785","3,778","2,922",NaN,"3,126","2,994",import
3,3,Bangladesh,"2,429","2,397","2,351","2,807",NaN,"2,700",import
4,4,European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import
...,...,...,...,...,...,...,...,...,...
22,22,Yemen,667,770,941,466,NaN,875,import
23,23,Chile,449,648,532,NaN,640,640,import
24,24,Kazakhstan,345,482,478,NaN,580,625,import
25,25,Other,"12,962","12,537","12,422",NaN,"12,177","11,653",import
26,26,Total,"53,161","53,735","58,704","56,105","57,527","59,012",import

* df.index.name

In [748]:
df1.index.name = 'Number'
df1

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export
1,Thailand,"10,612","6,695","3,739",NaN,"11,000","12,000",export
2,India,"4,700","5,800","8,406",NaN,"6,500","7,000",export
3,Australia,"3,735","3,600","3,400","3,120",NaN,"3,600",export
4,Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export
...,...,...,...,...,...,...,...,...
22,Malaysia,123,109,329,316,NaN,300,export
23,Korea_South,306,313,320,NaN,260,280,export
24,China,205,189,132,NaN,202,250,export
25,Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export
26,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export

In [749]:
df2.index.name = 'Number'
df2

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import
1,China,"4,086","3,808","6,379",NaN,"4,400","5,000",import
2,United_States,"2,785","3,778","2,922",NaN,"3,126","2,994",import
3,Bangladesh,"2,429","2,397","2,351","2,807",NaN,"2,700",import
4,European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import
...,...,...,...,...,...,...,...,...
22,Yemen,667,770,941,466,NaN,875,import
23,Chile,449,648,532,NaN,640,640,import
24,Kazakhstan,345,482,478,NaN,580,625,import
25,Other,"12,962","12,537","12,422",NaN,"12,177","11,653",import
26,Total,"53,161","53,735","58,704","56,105","57,527","59,012",import

* .index

In [750]:
df1.index

RangeIndex(start=0, stop=27, step=1, name='Number')

In [751]:
df2.index

RangeIndex(start=0, stop=27, step=1, name='Number')

**Use df.melt() and df.pivot() to reshape dataframes, specifically to make tidy dataframes.**

* df.melt()

In [752]:
df1_melted = df1.melt(id_vars = ['Country'],
         value_vars = ['2018 - 2019', '2019 - 2020'],
         var_name = 'Year',
         value_name = 'Weight (Tons)')

df1_melted

        Country         Year Weight (Tons)
0        Brazil  2018 - 2019        19,600
1      Thailand  2018 - 2019        10,612
2         India  2018 - 2019         4,700
3     Australia  2018 - 2019         3,735
4     Guatemala  2018 - 2019         2,125
..          ...          ...           ...
49     Malaysia  2019 - 2020           109
50  Korea_South  2019 - 2020           313
51        China  2019 - 2020           189
52        Other  2019 - 2020         4,735
53        Total  2019 - 2020        53,536

[54 rows x 3 columns]

In [753]:
df2_melted = df2.melt(id_vars = ['Country'],
         value_vars = ['2018 - 2019', '2019 - 2020'],
         var_name = 'Year',
         value_name = 'Weight (Tons)')

df2_melted

           Country         Year Weight (Tons)
0        Indonesia  2018 - 2019         5,362
1            China  2018 - 2019         4,086
2    United_States  2018 - 2019         2,785
3       Bangladesh  2018 - 2019         2,429
4   European_Union  2018 - 2019         2,374
..             ...          ...           ...
49           Yemen  2019 - 2020           770
50           Chile  2019 - 2020           648
51      Kazakhstan  2019 - 2020           482
52           Other  2019 - 2020        12,537
53           Total  2019 - 2020        53,735

[54 rows x 3 columns]

* df.pivot()

In [754]:
df1_melted.pivot(index='Country',
                 columns='Year',
                 values='Weight (Tons)')

Year                 2018 - 2019 2019 - 2020
Country
Algeria                      208         334
Australia                  3,735       3,600
Brazil                    19,600      19,280
China                        205         189
Colombia                     801         778
...                          ...         ...
Saudi_Arabia                 353         429
South_Africa               1,041       1,451
Thailand                  10,612       6,695
Total                     58,271      53,536
United_Arab_Emirates         209         187

[27 rows x 2 columns]

In [755]:
df2_melted.pivot(index='Country',
                 columns='Year',
                 values='Weight (Tons)')

Year                 2018 - 2019 2019 - 2020
Country
Algeria                    2,328       2,468
Bangladesh                 2,429       2,397
Canada                     1,268       1,245
Chile                        449         648
China                      4,086       3,808
...                          ...         ...
Total                     53,161      53,735
United_Arab_Emirates       1,579         751
United_States              2,785       3,778
Vietnam                      303       1,312
Yemen                        667         770

[27 rows x 2 columns]

**Combine dataframes using df.merge() and pd.concat() and know when to use these different methods.**

* df.merge()

In [756]:
df_merged = df1.merge(df2, on = 'Country', how = 'inner')
df_merged

,Country,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,Action_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y,Action_y
0,India,"4,700","5,800","8,406",NaN,"6,500","7,000",export,"1,300",900,"1,245",340,NaN,"1,000",import
1,United_Arab_Emirates,209,187,792,909,NaN,960,export,"1,579",751,"1,785",NaN,"1,750","1,875",import
2,European_Union,"2,411","1,459","1,278",NaN,913,905,export,"2,374","2,235","1,792","1,999","3,000","2,500",import
3,Morocco,497,664,681,NaN,775,780,export,"1,100","1,328","1,407",NaN,"1,503","1,603",import
4,Saudi_Arabia,353,429,370,NaN,700,750,export,"1,342","1,420","1,488",NaN,"1,720","1,950",import
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Malaysia,123,109,329,316,NaN,300,export,"2,139","1,966","2,142",NaN,"2,100","2,340",import
10,Korea_South,306,313,320,NaN,260,280,export,"1,999","1,926","1,934",NaN,"1,950","2,025",import
11,China,205,189,132,NaN,202,250,export,"4,086","3,808","6,379",NaN,"4,400","5,000",import
12,Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export,"12,962","12,537","12,422",NaN,"12,177","11,653",import
13,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export,"53,161","53,735","58,704","56,105","57,527","59,012",import

* pd.concat()

In [757]:
df_concat = pd.concat([df1, df2],
            axis = 1)
df_concat

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,,,,,,,,,
0,Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export,Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import
1,Thailand,"10,612","6,695","3,739",NaN,"11,000","12,000",export,China,"4,086","3,808","6,379",NaN,"4,400","5,000",import
2,India,"4,700","5,800","8,406",NaN,"6,500","7,000",export,United_States,"2,785","3,778","2,922",NaN,"3,126","2,994",import
3,Australia,"3,735","3,600","3,400","3,120",NaN,"3,600",export,Bangladesh,"2,429","2,397","2,351","2,807",NaN,"2,700",import
4,Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export,European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,Malaysia,123,109,329,316,NaN,300,export,Yemen,667,770,941,466,NaN,875,import
23,Korea_South,306,313,320,NaN,260,280,export,Chile,449,648,532,NaN,640,640,import
24,China,205,189,132,NaN,202,250,export,Kazakhstan,345,482,478,NaN,580,625,import
25,Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export,Other,"12,962","12,537","12,422",NaN,"12,177","11,653",import
26,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export,Total,"53,161","53,735","58,704","56,105","57,527","59,012",import

**Apply functions to a dataframe df.apply() and df.applymap()**

* df.apply()

In [758]:
df1_applied = df1.copy()

def custom_function(row):
    Country = row['Country']
    Action = row['Action']

    # Extract columns for summing (2018 - 2019 to 2023 - 2024)
    columns_to_sum = row.index[1:-2]

    # Convert columns to numeric and replace NaN values with 0
    numeric_values = pd.to_numeric(row[columns_to_sum].str.replace(',', ''), errors='coerce').fillna(0)

    total_sum = numeric_values.sum()

    # Format the total_sum with commas
    formatted_total_sum = f"{total_sum:,.0f}"

    result = f"{Country} total numeric values for {Action} from 2018 - 2024 is {formatted_total_sum} tons"

    return result

df1_applied['Total'] = df1_applied.apply(custom_function, axis=1)
df1_applied

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action,Total
Number,,,,,,,,,
0,Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export,Brazil total numeric values for export from 20...
1,Thailand,"10,612","6,695","3,739",NaN,"11,000","12,000",export,Thailand total numeric values for export from ...
2,India,"4,700","5,800","8,406",NaN,"6,500","7,000",export,India total numeric values for export from 201...
3,Australia,"3,735","3,600","3,400","3,120",NaN,"3,600",export,Australia total numeric values for export from...
4,Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export,Guatemala total numeric values for export from...
...,...,...,...,...,...,...,...,...,...
22,Malaysia,123,109,329,316,NaN,300,export,Malaysia total numeric values for export from ...
23,Korea_South,306,313,320,NaN,260,280,export,Korea_South total numeric values for export fr...
24,China,205,189,132,NaN,202,250,export,China total numeric values for export from 201...
25,Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export,Other total numeric values for export from 201...
26,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export,Total total numeric values for export from 201...

In [759]:
df2_applied = df2.copy()

def custom_function(row):
    Country = row['Country']
    Action = row['Action']

    # Extract columns for summing (2018 - 2019 to 2023 - 2024)
    columns_to_sum = row.index[1:-2]

    # Convert columns to numeric and replace NaN values with 0
    numeric_values = pd.to_numeric(row[columns_to_sum].str.replace(',', ''), errors='coerce').fillna(0)

    total_sum = numeric_values.sum()

    # Format the total_sum with commas
    formatted_total_sum = f"{total_sum:,.0f}"

    result = f"{Country} total numeric values for {Action} from 2018 - 2024 is {formatted_total_sum} tons"

    return result

df2_applied['Total'] = df2_applied.apply(custom_function, axis=1)
df2_applied

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action,Total
Number,,,,,,,,,
0,Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import,Indonesia total numeric values for import from...
1,China,"4,086","3,808","6,379",NaN,"4,400","5,000",import,China total numeric values for import from 201...
2,United_States,"2,785","3,778","2,922",NaN,"3,126","2,994",import,United_States total numeric values for import ...
3,Bangladesh,"2,429","2,397","2,351","2,807",NaN,"2,700",import,Bangladesh total numeric values for import fro...
4,European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import,European_Union total numeric values for import...
...,...,...,...,...,...,...,...,...,...
22,Yemen,667,770,941,466,NaN,875,import,Yemen total numeric values for import from 201...
23,Chile,449,648,532,NaN,640,640,import,Chile total numeric values for import from 201...
24,Kazakhstan,345,482,478,NaN,580,625,import,Kazakhstan total numeric values for import fro...
25,Other,"12,962","12,537","12,422",NaN,"12,177","11,653",import,Other total numeric values for import from 201...
26,Total,"53,161","53,735","58,704","56,105","57,527","59,012",import,Total total numeric values for import from 201...

* df.applymap()

In [760]:
df1_appliedmap = df1.applymap(lambda x: len(str(x)))
df1_appliedmap

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,6,6,6,6,6,6,6,6
1,8,6,5,5,3,6,6,6
2,5,5,5,5,3,5,5,6
3,9,5,5,5,5,3,5,6
4,9,5,5,5,5,5,5,6
...,...,...,...,...,...,...,...,...
22,8,3,3,3,3,3,3,6
23,11,3,3,3,3,3,3,6
24,5,3,3,3,3,3,3,6
25,5,5,5,5,3,5,5,6
26,5,6,6,6,6,6,6,6

In [761]:
df2_appliedmap = df2.applymap(lambda x: len(str(x)))
df2_appliedmap

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,9,5,5,5,5,5,5,6
1,5,5,5,5,3,5,5,6
2,13,5,5,5,3,5,5,6
3,10,5,5,5,5,3,5,6
4,14,5,5,5,5,5,5,6
...,...,...,...,...,...,...,...,...
22,5,3,3,3,3,3,3,6
23,5,3,3,3,3,3,3,6
24,10,3,3,3,3,3,3,6
25,5,6,6,6,3,6,6,6
26,5,6,6,6,6,6,6,6

**Find the data which satisfy specific condition using df.query()**

In [762]:
df_queried = df_merged.query("`Country` == 'Indonesia' or `Country` == 'Malaysia'")
df_queried

,Country,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,Action_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y,Action_y
5,Indonesia,0,11,97,NaN,440,450,export,"5,362","4,758","6,124","5,466","5,800","5,630",import
9,Malaysia,123,109,329,316,NaN,300,export,"2,139","1,966","2,142",NaN,"2,100","2,340",import

**Perform grouping and aggregating operations using df.groupby() and df.agg()**

* df.groupby()

In [763]:
df_grouped = df_merged.groupby(['Country']).count()
df_grouped

,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,Action_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y,Action_y
Country,,,,,,,,,,,,,,
Algeria,1,1,1,1,0,1,1,1,1,1,1,0,1,1
China,1,1,1,0,1,1,1,1,1,1,0,1,1,1
Egypt,1,1,1,1,0,1,1,1,1,1,1,1,1,1
European_Union,1,1,1,0,1,1,1,1,1,1,1,1,1,1
India,1,1,1,0,1,1,1,1,1,1,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Nigeria,1,1,1,1,1,1,1,1,1,1,0,1,1,1
Other,1,1,1,0,1,1,1,1,1,1,0,1,1,1
Saudi_Arabia,1,1,1,0,1,1,1,1,1,1,0,1,1,1
Total,1,1,1,1,1,1,1,1,1,1,1,1,1,1
United_Arab_Emirates,1,1,1,1,0,1,1,1,1,1,0,1,1,1

* df.agg()

In [764]:
df1_copy = df1.copy()

year_columns = ['2018 - 2019', '2019 - 2020', '2020 - 2021', '2021 - 2022', '2022 - 2023', 'May 2023 - 2024']
df1_copy[year_columns] = df1_copy[year_columns].replace(',', '', regex=True).astype(float)


df_agg1 = df1_copy[year_columns].agg(['min', 'max'])

# Format the result to include commas
formatted_df_agg1 = df_agg1.applymap(lambda x: f"{x:,.0f}")
formatted_df_agg1

,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024
min,0,11,0,300,202,250
max,"58,271","53,536","63,925","64,955","66,085","72,104"

In [765]:
df2_copy = df2.copy()

year_columns = ['2018 - 2019', '2019 - 2020', '2020 - 2021', '2021 - 2022', '2022 - 2023', 'May 2023 - 2024']
df2_copy[year_columns] = df2_copy[year_columns].replace(',', '', regex=True).astype(float)


df_agg2 = df2_copy[year_columns].agg(['min', 'max'])

# Format the result to include commas
formatted_df_agg2 = df_agg2.applymap(lambda x: f"{x:,.0f}")
formatted_df_agg2

,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024
min,303,432,478,340,580,625
max,"53,161","53,735","58,704","56,105","57,527","59,012"

**Perform aggregating methods on grouped or ungrouped objects such as finding the minimum, maximum and sum of values in a dataframe using df.agg().**

* Ungrouped Objects

In [766]:
df_merged_copy = df_merged.copy()

year_columns = ['2018 - 2019_x',
                '2019 - 2020_x',
                '2020 - 2021_x',
                '2021 - 2022_x',
                '2022 - 2023_x',
                'May 2023 - 2024_x',
                '2018 - 2019_y',
                '2019 - 2020_y',
                '2020 - 2021_y',
                '2021 - 2022_y',
                '2022 - 2023_y',
                'May 2023 - 2024_y']

df_merged_copy[year_columns] = df_merged_copy[year_columns].replace(',', '', regex=True).astype(float)

df_agg2 = df_merged_copy[year_columns].agg(['min', 'max', 'sum'])

# Format the result to include commas
formatted_df_agg2 = df_agg2.applymap(lambda x: f"{x:,.0f}")
formatted_df_agg2

,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y
min,0,11,97,300,202,250,860,751,830,340,830,930
max,"58,271","53,536","63,925","64,955","66,085","72,104","53,161","53,735","58,704","56,105","57,527","59,012"
sum,"72,794","68,366","81,786","67,196","80,239","88,505","92,462","90,552","100,389","66,985","94,707","99,749"

* Grouped Objects

In [767]:
df_merged_copy = df_merged.copy()

year_columns = ['2018 - 2019_x',
                '2019 - 2020_x',
                '2020 - 2021_x',
                '2021 - 2022_x',
                '2022 - 2023_x',
                'May 2023 - 2024_x',
                '2018 - 2019_y',
                '2019 - 2020_y',
                '2020 - 2021_y',
                '2021 - 2022_y',
                '2022 - 2023_y',
                'May 2023 - 2024_y']

df_merged_copy[year_columns] = df_merged_copy[year_columns].replace(',', '', regex=True).astype(float)

# Group by the relevant columns
grouped = df_merged_copy.groupby('Country')

df_agg2 = grouped[year_columns].agg(['min', 'max', 'sum'])

# Format the result to include commas
formatted_df_agg2 = df_agg2.applymap(lambda x: f"{x:,.0f}")
formatted_df_agg2

                     2018 - 2019_x                 2019 - 2020_x          \
                               min     max     sum           min     max
Country
Algeria                        208     208     208           334     334
China                          205     205     205           189     189
Egypt                          200     200     200           300     300
European_Union               2,411   2,411   2,411         1,459   1,459
India                        4,700   4,700   4,700         5,800   5,800
...                            ...     ...     ...           ...     ...
Nigeria                        300     300     300           300     300
Other                        5,011   5,011   5,011         4,735   4,735
Saudi_Arabia                   353     353     353           429     429
Total                       58,271  58,271  58,271        53,536  53,536
United_Arab_Emirates           209     209     209           187     187

                             2020 - 2021_x                 2021 - 2022_x  ...  \
                         sum           min     max     sum           min  ...
Country                                                                   ...
Algeria                  334           364     364     364           366  ...
China                    189           132     132     132           nan  ...
Egypt                    300           300     300     300           300  ...
European_Union         1,459         1,278   1,278   1,278           nan  ...
India                  5,800         8,406   8,406   8,406           nan  ...
...                      ...           ...     ...     ...           ...  ...
Nigeria                  300           300     300     300           350  ...
Other                  4,735         4,492   4,492   4,492           nan  ...
Saudi_Arabia             429           370     370     370           nan  ...
Total                 53,536        63,925  63,925  63,925        64,955  ...
United_Arab_Emirates     187           792     792     792           909  ...

                     2020 - 2021_y 2021 - 2022_y                  \
                               sum           min     max     sum
Country
Algeria                      2,257         2,245   2,245   2,245
China                        6,379           nan     nan       0
Egypt                          830           830     830     830
European_Union               1,792         1,999   1,999   1,999
India                        1,245           340     340     340
...                            ...           ...     ...     ...
Nigeria                      1,880           nan     nan       0
Other                       12,422           nan     nan       0
Saudi_Arabia                 1,488           nan     nan       0
Total                       58,704        56,105  56,105  56,105
United_Arab_Emirates         1,785           nan     nan       0

                     2022 - 2023_y                 May 2023 - 2024_y          \
                               min     max     sum               min     max
Country
Algeria                        nan     nan       0             2,301   2,301
China                        4,400   4,400   4,400             5,000   5,000
Egypt                          830     830     830               930     930
European_Union               3,000   3,000   3,000             2,500   2,500
India                          nan     nan       0             1,000   1,000
...                            ...     ...     ...               ...     ...
Nigeria                      1,950   1,950   1,950             1,930   1,930
Other                       12,177  12,177  12,177            11,653  11,653
Saudi_Arabia                 1,720   1,720   1,720             1,950   1,950
Total                       57,527  57,527  57,527            59,012  59,012
United_Arab_Emirates         1,750   1,750   1,750             1,875   1,875


                         sum
Country
Algeria                2,301
China                  5,000
Egypt                    930
European_Union         2,500
India                  1,000
...                      ...
Nigeria                1,930
Other                 11,653
Saudi_Arabia           1,950
Total                 59,012
United_Arab_Emirates   1,875

[14 rows x 36 columns]

**Remove or fill missing values in a dataframe with df.dropna() and df.fillna() please practice using different method of filling missing value.**

* df.dropna()

In [768]:
df1_dropped = df1.dropna()
df1_dropped

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export
4,Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export
12,South_Africa,"1,041","1,451","1,007",595,635,650,export
19,Nigeria,300,300,300,350,350,355,export
20,Mauritius,347,396,369,324,335,335,export
26,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export

In [769]:
df2_dropped = df2.dropna()
df2_dropped

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import
4,European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import
12,Vietnam,303,"1,312","1,325","1,490","1,520","1,575",import
19,Iran,935,"1,111","1,421",973,989,"1,000",import
20,Egypt,860,830,830,830,830,930,import
26,Total,"53,161","53,735","58,704","56,105","57,527","59,012",import

* df.fillna()

In [770]:
df_filled = df_merged.fillna('-')
df_filled

,Country,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,Action_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y,Action_y
0,India,"4,700","5,800","8,406",-,"6,500","7,000",export,"1,300",900,"1,245",340,-,"1,000",import
1,United_Arab_Emirates,209,187,792,909,-,960,export,"1,579",751,"1,785",-,"1,750","1,875",import
2,European_Union,"2,411","1,459","1,278",-,913,905,export,"2,374","2,235","1,792","1,999","3,000","2,500",import
3,Morocco,497,664,681,-,775,780,export,"1,100","1,328","1,407",-,"1,503","1,603",import
4,Saudi_Arabia,353,429,370,-,700,750,export,"1,342","1,420","1,488",-,"1,720","1,950",import
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Malaysia,123,109,329,316,-,300,export,"2,139","1,966","2,142",-,"2,100","2,340",import
10,Korea_South,306,313,320,-,260,280,export,"1,999","1,926","1,934",-,"1,950","2,025",import
11,China,205,189,132,-,202,250,export,"4,086","3,808","6,379",-,"4,400","5,000",import
12,Other,"5,011","4,735","4,492",-,"4,014","3,706",export,"12,962","12,537","12,422",-,"12,177","11,653",import
13,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export,"53,161","53,735","58,704","56,105","57,527","59,012",import

**Practice imputing missing values using the SimpleImputer Class in sklearn**

In [771]:
from sklearn.impute import SimpleImputer

df1_copy = df1.copy()

imputer = SimpleImputer(strategy='mean')

year_columns_to_input = ['2021 - 2022', '2022 - 2023']

df1_copy[year_columns_to_input] = df1_copy[year_columns_to_input].applymap(lambda x: float(str(x).replace(',', '')))
df1_copy[year_columns_to_input] = imputer.fit_transform(df1_copy[year_columns_to_input])

df1_copy[year_columns_to_input] = df1_copy[year_columns_to_input].applymap(lambda x: f"{x:,.0f}")

df1_copy

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,Brazil,"19,600","19,280","32,150","25,950","28,200","32,398",export
1,Thailand,"10,612","6,695","3,739","8,272","11,000","12,000",export
2,India,"4,700","5,800","8,406","8,272","6,500","7,000",export
3,Australia,"3,735","3,600","3,400","3,120","6,019","3,600",export
4,Guatemala,"2,125","1,858","1,395","1,651","1,657","1,662",export
...,...,...,...,...,...,...,...,...
22,Malaysia,123,109,329,316,"6,019",300,export
23,Korea_South,306,313,320,"8,272",260,280,export
24,China,205,189,132,"8,272",202,250,export
25,Other,"5,011","4,735","4,492","8,272","4,014","3,706",export
26,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export

In [772]:
from sklearn.impute import SimpleImputer

df2_copy = df2.copy()

imputer = SimpleImputer(strategy='mean')

year_columns_to_input = ['2021 - 2022', '2022 - 2023']

df2_copy[year_columns_to_input] = df2_copy[year_columns_to_input].applymap(lambda x: float(str(x).replace(',', '')))
df2_copy[year_columns_to_input] = imputer.fit_transform(df2_copy[year_columns_to_input])

df2_copy[year_columns_to_input] = df2_copy[year_columns_to_input].applymap(lambda x: f"{x:,.0f}")

df2_copy

,Country,2018 - 2019,2019 - 2020,2020 - 2021,2021 - 2022,2022 - 2023,May 2023 - 2024,Action
Number,,,,,,,,
0,Indonesia,"5,362","4,758","6,124","5,466","5,800","5,630",import
1,China,"4,086","3,808","6,379","6,243","4,400","5,000",import
2,United_States,"2,785","3,778","2,922","6,243","3,126","2,994",import
3,Bangladesh,"2,429","2,397","2,351","2,807","5,076","2,700",import
4,European_Union,"2,374","2,235","1,792","1,999","3,000","2,500",import
...,...,...,...,...,...,...,...,...
22,Yemen,667,770,941,466,"5,076",875,import
23,Chile,449,648,532,"6,243",640,640,import
24,Kazakhstan,345,482,478,"6,243",580,625,import
25,Other,"12,962","12,537","12,422","6,243","12,177","11,653",import
26,Total,"53,161","53,735","58,704","56,105","57,527","59,012",import

# **Extra Miles** 🌟

**clean your text data using regex function**

*   Before cleaning the text data

In [773]:
df_merged

,Country,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,Action_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y,Action_y
0,India,"4,700","5,800","8,406",NaN,"6,500","7,000",export,"1,300",900,"1,245",340,NaN,"1,000",import
1,United_Arab_Emirates,209,187,792,909,NaN,960,export,"1,579",751,"1,785",NaN,"1,750","1,875",import
2,European_Union,"2,411","1,459","1,278",NaN,913,905,export,"2,374","2,235","1,792","1,999","3,000","2,500",import
3,Morocco,497,664,681,NaN,775,780,export,"1,100","1,328","1,407",NaN,"1,503","1,603",import
4,Saudi_Arabia,353,429,370,NaN,700,750,export,"1,342","1,420","1,488",NaN,"1,720","1,950",import
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Malaysia,123,109,329,316,NaN,300,export,"2,139","1,966","2,142",NaN,"2,100","2,340",import
10,Korea_South,306,313,320,NaN,260,280,export,"1,999","1,926","1,934",NaN,"1,950","2,025",import
11,China,205,189,132,NaN,202,250,export,"4,086","3,808","6,379",NaN,"4,400","5,000",import
12,Other,"5,011","4,735","4,492",NaN,"4,014","3,706",export,"12,962","12,537","12,422",NaN,"12,177","11,653",import
13,Total,"58,271","53,536","63,925","64,955","66,085","72,104",export,"53,161","53,735","58,704","56,105","57,527","59,012",import

* Cleaning

In [774]:
import re

In [775]:
def clean_text_with_regex(text):
    if pd.notna(text):  # Skip NaN values
        cleaned_text = re.sub(r'[^\w\s]+', '', text)  # Remove non-alphanumeric characters
        return cleaned_text
    else:
        return text

columns_to_clean = ['2018 - 2019_x',
                    '2019 - 2020_x',
                    '2020 - 2021_x',
                    '2021 - 2022_x',
                    '2022 - 2023_x',
                    'May 2023 - 2024_x',
                    '2018 - 2019_y',
                    '2019 - 2020_y',
                    '2020 - 2021_y',
                    '2021 - 2022_y',
                    '2022 - 2023_y',
                    'May 2023 - 2024_y']

for column in columns_to_clean:
    df_merged[column] = df_merged[column].apply(clean_text_with_regex)

*  After cleaning the text data

In [776]:
df_merged

,Country,2018 - 2019_x,2019 - 2020_x,2020 - 2021_x,2021 - 2022_x,2022 - 2023_x,May 2023 - 2024_x,Action_x,2018 - 2019_y,2019 - 2020_y,2020 - 2021_y,2021 - 2022_y,2022 - 2023_y,May 2023 - 2024_y,Action_y
0,India,4700,5800,8406,NaN,6500,7000,export,1300,900,1245,340,NaN,1000,import
1,United_Arab_Emirates,209,187,792,909,NaN,960,export,1579,751,1785,NaN,1750,1875,import
2,European_Union,2411,1459,1278,NaN,913,905,export,2374,2235,1792,1999,3000,2500,import
3,Morocco,497,664,681,NaN,775,780,export,1100,1328,1407,NaN,1503,1603,import
4,Saudi_Arabia,353,429,370,NaN,700,750,export,1342,1420,1488,NaN,1720,1950,import
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Malaysia,123,109,329,316,NaN,300,export,2139,1966,2142,NaN,2100,2340,import
10,Korea_South,306,313,320,NaN,260,280,export,1999,1926,1934,NaN,1950,2025,import
11,China,205,189,132,NaN,202,250,export,4086,3808,6379,NaN,4400,5000,import
12,Other,5011,4735,4492,NaN,4014,3706,export,12962,12537,12422,NaN,12177,11653,import
13,Total,58271,53536,63925,64955,66085,72104,export,53161,53735,58704,56105,57527,59012,import

**clean the text and nested json in**
> https://raw.githubusercontent.com/nnqomariyah/Fundamentals_of_Data_Science/main/week_3/data/movies_metadata.csv

In [777]:
import json

In [778]:
url = 'https://raw.githubusercontent.com/nnqomariyah/Fundamentals_of_Data_Science/main/week_3/data/movies_metadata.csv'
df3 = pd.read_csv(url)

<ipython-input-778-8ad7edba1c73>:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(url)

*   Before cleaning the text data

In [779]:
df3.info()
df3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

*   Cleaning

In [780]:
def clean_text(text):
    if pd.notna(text): # Skip NaN values
        cleaned_text = re.sub(r'\s+', ' ', text) # Remove extra whitespace and replace with a single space
        return cleaned_text
    else:
        return text

columns_to_clean = ['original_title', 'overview', 'tagline', 'title', 'tagline']

for column in columns_to_clean:
    df3[column] = df3[column].apply(clean_text)

# 'belongs_to_collection' column
def clean_belongs_to_collection(collection):
    if pd.notna(collection):
        match = re.search(r"'name':\s*'([^']+)'", collection) # Extract the 'name' field
        if match:
            return match.group(1)
    return None

df3['belongs_to_collection'] = df3['belongs_to_collection'].apply(clean_belongs_to_collection)

# 'production_companies', 'production_countries' columns
def clean_column(column):
    if pd.notna(column):
        try:
            data = json.loads(column.replace("'", "\""))
            if isinstance(data, list):
                item_list = [item['name'] for item in data]
                return ', '.join(item_list)
        except (json.JSONDecodeError, KeyError):
            return None
    return None

df3['production_companies'] = df3['production_companies'].apply(clean_column)
df3['production_countries'] = df3['production_countries'].apply(clean_column)

# 'runtime' column
def format_runtime(runtime):
    if pd.notna(runtime):
        return f'{int(runtime)} mins'
    return None

df3['runtime'] = df3['runtime'].apply(format_runtime)

# 'genres' column
df3['genres'] = df3['genres'].apply(lambda x: eval(x) if pd.notna(x) else []) # Convert to a list of dictionaries
df3['genres'] = df3['genres'].apply(lambda x: ', '.join(item['name'] for item in x))

# 'spoken_languages' column
df3['spoken_languages'] = df3['spoken_languages'].apply(lambda x: eval(x) if pd.notna(x) else [])
df3['spoken_languages_names'] = df3['spoken_languages'].apply(lambda x: ', '.join(item['name'] for item in x))
df3 = df3.drop(columns=['spoken_languages']) # Drop original column

# 'budget' column
def clean_budget(budget):
    if pd.notna(budget):
        numeric_budget = re.sub(r'[^\d]+', '', budget) # Remove non-numeric characters
        return numeric_budget
    return None

df3['budget'] = df3['budget'].apply(clean_budget)

# Add commas for numbers
def format_with_commas(number):
    if pd.notna(number):
        return '{:,}'.format(int(number))
    return None

df3['budget'] = df3['budget'].apply(format_with_commas)
df3['revenue'] = df3['revenue'].apply(format_with_commas)

# 'vote_average' column
df3['vote_average'] = df3['vote_average'].apply(lambda x: float(x) if pd.notna(x) else None)

# 'vote_count' column
df3['vote_count'] = df3['vote_count'].apply(lambda x: f'{int(x):,}' if pd.notna(x) else None)

# Dropping NaN values
df3.dropna(inplace=True)

# Drop 'adult', 'video', 'original_language' columns
df3.drop(columns=['adult', 'video', 'original_language'], inplace=True)

# Rearranging columns
columns_order = [
    'id',
    'imdb_id',
    'title',
    'original_title',
    'spoken_languages_names',
    'belongs_to_collection',
    'release_date',
    'genres',
    'tagline',
    'overview',
    'runtime',
    'production_companies',
    'production_countries',
    'budget',
    'revenue',
    'vote_average',
    'vote_count',
    'popularity',
    'homepage',
    'status',
    'poster_path'
]
df3 = df3[columns_order]

# Renaming columns
columns_rename = {
    'id': 'ID',
    'imdb_id': 'IMDB ID',
    'title': 'Title',
    'original_title': 'Original Title',
    'spoken_languages_names': 'Spoken Languages',
    'belongs_to_collection': 'Collection',
    'release_date': 'Release Date',
    'genres': 'Genres',
    'tagline': 'Tagline',
    'overview': 'Overview',
    'runtime': 'Runtime',
    'production_companies': 'Production Companies',
    'production_countries': 'Production Countries',
    'budget': 'Budget',
    'revenue': 'Revenue',
    'vote_average': 'Vote Average',
    'vote_count': 'Vote Count',
    'popularity': 'Popularity',
    'homepage': 'Homepage',
    'status': 'Status',
    'poster_path': 'Poster Path'
}

# Rename the columns in the DataFrame
df3.rename(columns = columns_rename, inplace = True)

*   After cleaning the text data

In [781]:
df3.info()
df3.to_csv('cleaned_movies_metadata.csv', index=False)
df3

<class 'pandas.core.frame.DataFrame'>
Int64Index: 658 entries, 9 to 45029
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    658 non-null    object
 1   IMDB ID               658 non-null    object
 2   Title                 658 non-null    object
 3   Original Title        658 non-null    object
 4   Spoken Languages      658 non-null    object
 5   Collection            658 non-null    object
 6   Release Date          658 non-null    object
 7   Genres                658 non-null    object
 8   Tagline               658 non-null    object
 9   Overview              658 non-null    object
 10  Runtime               658 non-null    object
 11  Production Companies  658 non-null    object
 12  Production Countries  658 non-null    object
 13  Budget                658 non-null    object
 14  Revenue               658 non-null    object
 15  Vote Average          658 non-null    float64
 16  Vote Count            658 non-null    object
 17  Popularity            658 non-null    object
 18  Homepage              658 non-null    object
 19  Status                658 non-null    object
 20  Poster Path           658 non-null    object
dtypes: float64(1), object(20)
memory usage: 113.1+ KB

,ID,IMDB ID,Title,Original Title,Spoken Languages,Collection,Release Date,Genres,Tagline,Overview,...,Production Companies,Production Countries,Budget,Revenue,Vote Average,Vote Count,Popularity,Homepage,Status,Poster Path
9,710,tt0113189,GoldenEye,GoldenEye,"English, Pусский, Español",James Bond Collection,1995-11-16,"Adventure, Action, Thriller",No limits. No fears. No substitutes.,James Bond must unmask the mysterious head of ...,...,"United Artists, Eon Productions","United Kingdom, United States of America","58,000,000","352,194,034",6.6,"1,194",14.686036,http://www.mgm.com/view/movie/757/Goldeneye/,Released,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg
68,10634,tt0113118,Friday,Friday,English,Friday Collection,1995-04-26,Comedy,A lot can go down between thursday and saturda...,Craig and Smokey are two guys in Los Angeles h...,...,New Line Cinema,United States of America,"3,500,000","28,215,918",7.0,513,14.56965,http://www.newline.com/properties/friday.html,Released,/kkoGT4bnK5oGiNbzGGcXzrXMSxn.jpg
69,755,tt0116367,From Dusk Till Dawn,From Dusk Till Dawn,"English, Español",From Dusk Till Dawn Collection,1996-01-19,"Horror, Action, Thriller, Crime",One night is all that stands between them and ...,Seth Gecko and his younger brother Richard are...,...,"A Band Apart, Dimension Films, Los Hooligans P...",United States of America,"19,000,000","25,836,616",6.9,"1,644",15.339153,http://www.miramax.com/movie/from-dusk-till-dawn/,Released,/ce0d4kM5KxT4x1Oq8JkSuNYevri.jpg
153,5894,tt0112541,Blue in the Face,Blue in the Face,English,Brooklyn Cigar Store Collection,1995-09-15,Comedy,Welcome to the planet Brooklyn.,"Auggie runs a small tobacco shop in Brooklyn, ...",...,"Miramax Films, InterAL",United States of America,"2,000,000","1,275,000",6.8,28,11.528147,http://miramax.com/movie/blue-in-the-face/,Released,/qa9yf3OlfXbYBb0af0mpawGB6TI.jpg
178,9070,tt0113820,Mighty Morphin Power Rangers: The Movie,Mighty Morphin Power Rangers: The Movie,English,Power Rangers Collection,1995-06-30,"Action, Adventure, Science Fiction, Family, Fa...",The Power Is On!,Power up with six incredible teens who out-man...,...,"Twentieth Century Fox Film Corporation, Saban ...","Japan, United States of America","15,000,000","66,000,000",5.2,153,7.024227,http://www.powerrangers.com/,Released,/A3ijhraMN0tvpDnPoyVP7NulkSr.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44050,294682,tt3474600,Little Forest: Summer/Autumn,リトル・フォレスト 夏・秋,日本語,Little Forest Collection,2014-08-30,Drama,Back to nature.,"Abandoned by her mother, young Ichiko leaves h...",...,Shochiku,Japan,0,0,8.3,16,1.252833,https://web.archive.org/web/20160111092554/htt...,Released,/87FWLJdViF9p8vysGBFcXMXXlZp.jpg
44274,281338,tt3450958,War for the Planet of the Apes,War for the Planet of the Apes,English,Planet of the Apes (Reboot) Collection,2017-07-11,"Drama, Science Fiction, War",For freedom. For family. For the planet.,Caesar and his apes are forced into a deadly c...,...,Chernin Entertainment,"Canada, United States of America","152,000,000","369,907,963",6.7,"1,675",146.161786,http://www.foxmovies.com/movies/war-for-the-pl...,Released,/3vYhLLxrTtZLysXtIWktmd57Snv.jpg
44674,336890,tt2417712,Goon: Last of the Enforcers,Goon: Last of the Enforcers,English,Goon Collection,2017-03-17,Comedy,Glatt's Back!,"During a pro lockout, Doug ""The Thug"" Glatt is...",...,Caramel Film,Canada,0,0,6.0,35,6.365691,https://www.facebook.com/GoonFilm/?fref=ts,Released,/emio9KDrLXqqX4wXa4YTacBQXG.jpg
44842,335988,tt3371366,Transformers: The Last Knight,Transformers: The Last Knight,English,Transformers Collection,2017-06-21,"Action, Science Fiction, Thriller, Adventure","For one world to live, the other must die.","Autobots and Decepticons are at war, with huma...",...,"Paramount Pictures, Di Bonaventura Pictures, A...",United States of America,"260,000,000","604,942,143",6.2,"1,440",39.186819,http://www.transformersmovie.com/,Released,/s5HQf2Gb3lIO2cRcFwNL9sn1o1o.jpg
45029,417489,tt4738174,Bon Cop Bad Cop 2,Bon Cop Bad Cop 2,"English, Français",Bon Cop Bad Cop Collection,2017-05-12,"Crime, Comedy, Action","It's okay America, we've got your back.",Ward and Bouchard must face an important car t...,...,"Item 7, Jessie Films",Canada,0,0,6.8,5,7.580299,http://bcbc2.ca/en/,Released,/qY4RGT6Ky1Z46BWaKohTlNp9ncU.jpg